#!/usr/bin/env bash
declare -a options=("Reboot" "Shutdown" "Suspend" "Quit")
case $(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Shutdown menu:' "${@}") in
    'Reboot')   systemctl reboot;;        
    'Shutdown') systemctl poweroff;;
    'Suspend')  systemctl suspend;;
esac