#!/bin/sh
read -r a b c d <<<$(curl -s "https://wttr.in/esplechin?format=j1" | jq '.current_condition[0]'| jq '.temp_C, .winddir16Point, .windspeedKmph, .precipMM' | sed 's/"//g' | tr '\n' ' ')
echo " ${a}°C  ${b} ${c}Km/h  ${d}mm"